development:
  adapter: postgresql
  encoding: unicode
  database: teamwork_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: teamwork_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: teamwork_production
  pool: 5
  username: postgres
  password: postgres
